name: fixit_admin
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  file_picker: ^8.0.0+1
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  logger: ^2.2.0
  oktoast: ^3.4.0
  pointer_interceptor: ^0.10.1
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
